// Curated demo data for reporting and presentation.
// Intentional scope: fewer records, stronger story, no seed media.

const tourismPoints = [
  {
    name: 'Hồ Hoàn Kiếm',
    location: { type: 'Point', coordinates: [105.8544, 21.0285] },
    category: 'Văn hóa',
    highlights: 'Không gian biểu tượng của Thủ đô, phù hợp mở đầu tuyến city tour và học phần lịch sử - văn hóa.',
    description: 'Điểm trung tâm thuận tiện cho tuyến tham quan nội đô, tổ chức briefing đoàn và hoạt động trải nghiệm văn hóa.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Văn Miếu Quốc Tử Giám',
    location: { type: 'Point', coordinates: [105.8356, 21.0294] },
    category: 'Lịch sử',
    highlights: 'Di tích giáo dục tiêu biểu, phù hợp bài giảng về tài nguyên nhân văn và du lịch học đường.',
    description: 'Quần thể di tích giàu giá trị lịch sử, thuận lợi tổ chức tour ngắn và thuyết minh chuyên đề.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Chùa Một Cột',
    location: { type: 'Point', coordinates: [105.8339, 21.0359] },
    category: 'Tâm linh',
    highlights: 'Điểm dừng biểu tượng, dễ kết hợp trong tuyến tham quan nội đô và bài học du lịch tâm linh.',
    description: 'Không gian nhỏ nhưng có giá trị nhận diện cao, phù hợp làm điểm dừng chân ngắn trên tuyến Hà Nội.',
    role: 'Điểm dừng chân',
    images: [],
    videos: [],
  },
  {
    name: 'Vịnh Hạ Long',
    location: { type: 'Point', coordinates: [107.0448, 20.9101] },
    category: 'Tự nhiên',
    highlights: 'Di sản thiên nhiên thế giới, điểm nhấn chủ lực cho tuyến biển đảo và tour khách đoàn.',
    description: 'Điểm đến có sức hút cao, thích hợp xây dựng case study về định giá tour, dịch vụ và khai thác tuyến.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Hang Sửng Sốt',
    location: { type: 'Point', coordinates: [107.1089, 20.8841] },
    category: 'Tự nhiên',
    highlights: 'Điểm tham quan tiêu biểu trên hành trình tham quan vịnh, phù hợp minh họa dịch vụ tàu và vé tham quan.',
    description: 'Hang động nổi bật về cảnh quan, thường xuất hiện trong chương trình tour 2 ngày 1 đêm tại Hạ Long.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Đảo Ti Tốp',
    location: { type: 'Point', coordinates: [107.0667, 20.9167] },
    category: 'Tự nhiên',
    highlights: 'Điểm dừng chân đẹp, phù hợp minh họa hoạt động check-in và nghỉ ngơi trong tour cao điểm.',
    description: 'Đảo nhỏ có bãi tắm và điểm ngắm cảnh, thường kết hợp với du thuyền và chương trình team building nhẹ.',
    role: 'Điểm dừng chân',
    images: [],
    videos: [],
  },
  {
    name: 'Cố đô Huế',
    location: { type: 'Point', coordinates: [107.5905, 16.4637] },
    category: 'Văn hóa',
    highlights: 'Tài nguyên văn hóa đặc sắc, phù hợp tuyến di sản và tour học tập chuyên đề.',
    description: 'Điểm lõi của tuyến miền Trung, thuận lợi kết hợp lưu trú, ẩm thực và vé tham quan di tích.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Đèo Hải Vân',
    location: { type: 'Point', coordinates: [108.1289, 16.1994] },
    category: 'Tự nhiên',
    highlights: 'Điểm chuyển tiếp cảnh quan ấn tượng, dễ minh họa trải nghiệm tuyến đường và thời gian di chuyển.',
    description: 'Cung đường ngắm cảnh nổi bật giữa Huế và Đà Nẵng, phù hợp đưa vào phần trực quan bản đồ tuyến.',
    role: 'Điểm dừng chân',
    images: [],
    videos: [],
  },
  {
    name: 'Bà Nà Hills',
    location: { type: 'Point', coordinates: [108.0037, 15.9994] },
    category: 'Sinh thái',
    highlights: 'Điểm vui chơi có vé cao, rất phù hợp để minh họa chênh lệch doanh thu - chi phí trong dự toán.',
    description: 'Khu du lịch quy mô lớn, thường là điểm tạo khác biệt giá bán giữa các gói tour miền Trung.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Phố cổ Hội An',
    location: { type: 'Point', coordinates: [108.3380, 15.8801] },
    category: 'Văn hóa',
    highlights: 'Điểm đến nổi tiếng, phù hợp tour di sản, du lịch học đường và trải nghiệm ban đêm.',
    description: 'Không gian di sản đặc trưng, dễ kết hợp với ẩm thực địa phương và chương trình trải nghiệm văn hóa.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Thánh địa Mỹ Sơn',
    location: { type: 'Point', coordinates: [108.1270, 15.7724] },
    category: 'Lịch sử',
    highlights: 'Điểm di sản giúp đa dạng hóa nội dung học liệu về văn hóa Chăm và khai thác tuyến miền Trung.',
    description: 'Phù hợp làm điểm tham quan chuyên đề trong tour khảo sát cho giảng viên và sinh viên ngành du lịch.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Dinh Độc Lập',
    location: { type: 'Point', coordinates: [106.6953, 10.7779] },
    category: 'Lịch sử',
    highlights: 'Điểm tham quan tiêu biểu của TP.HCM, phù hợp case city tour và tour khách đoàn doanh nghiệp.',
    description: 'Dễ kết hợp với các điểm trung tâm khác để mô phỏng sản phẩm city tour nửa ngày hoặc một ngày.',
    role: 'Điểm tham quan chính',
    images: [],
    videos: [],
  },
  {
    name: 'Chợ Bến Thành',
    location: { type: 'Point', coordinates: [106.6980, 10.7719] },
    category: 'Văn hóa',
    highlights: 'Điểm dừng mua sắm và trải nghiệm đời sống đô thị, phù hợp minh họa dịch vụ bổ trợ trên tour.',
    description: 'Điểm dễ nhận diện, hỗ trợ kể câu chuyện về city tour, mua sắm và dịch vụ hỗ trợ khách đoàn.',
    role: 'Điểm dừng chân',
    images: [],
    videos: [],
  },
];

const serviceProviders = [
  {
    name: 'Khách sạn Silk Path Hà Nội',
    serviceType: 'accommodation',
    subType: 'hotel',
    location: { type: 'Point', coordinates: [105.8418, 21.0298] },
    address: '195-199 Hàng Bông, Hoàn Kiếm, Hà Nội',
    serviceArea: 'Địa phương',
    contact: { phone: '024 3266 5555', website: 'https://silkpathhotel.com' },
    priceRange: 'Cao cấp',
    description: 'Khách sạn trung tâm, phù hợp đoàn khảo sát và khách công vụ.',
    rating: 4.6,
    educationalNotes: 'Phù hợp minh họa phân khúc lưu trú đô thị cao cấp cho đoàn học tập.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Du thuyền Paradise Elegance',
    serviceType: 'accommodation',
    subType: 'resort',
    location: { type: 'Point', coordinates: [107.0448, 20.9101] },
    address: 'Cảng tàu khách quốc tế Tuần Châu, Hạ Long',
    serviceArea: 'Tuyến',
    contact: { phone: '1900 636 099', website: 'https://paradisevietnam.com' },
    priceRange: 'Cao cấp',
    description: 'Dịch vụ lưu trú cao cấp trên vịnh, phù hợp tour doanh nghiệp và khách cao cấp.',
    rating: 4.8,
    educationalNotes: 'Minh họa mô hình lưu trú gắn với trải nghiệm tuyến biển đảo.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Pilgrimage Village Huế',
    serviceType: 'accommodation',
    subType: 'resort',
    location: { type: 'Point', coordinates: [107.5905, 16.4637] },
    address: '130 Minh Mạng, Huế',
    serviceArea: 'Địa phương',
    contact: { phone: '0234 3885 461', website: 'https://pilgrimagevillage.com' },
    priceRange: 'Cao cấp',
    description: 'Khu nghỉ dưỡng phù hợp tour di sản và chương trình khách đoàn chất lượng cao.',
    rating: 4.7,
    educationalNotes: 'Dùng tốt trong case study định giá dịch vụ lưu trú tour miền Trung.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Sala Đà Nẵng Beach Hotel',
    serviceType: 'accommodation',
    subType: 'hotel',
    location: { type: 'Point', coordinates: [108.2448, 16.0678] },
    address: '36-38 Lâm Hoành, Sơn Trà, Đà Nẵng',
    serviceArea: 'Địa phương',
    contact: { phone: '0236 3658 555', website: 'https://saladanangbeach.com' },
    priceRange: 'Trung cấp',
    description: 'Khách sạn phù hợp đoàn sinh viên, khảo sát tuyến và tour công ty cỡ vừa.',
    rating: 4.5,
    educationalNotes: 'Minh họa lựa chọn lưu trú cân bằng giữa giá và chất lượng.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Nhà hàng Ngon Garden Hà Nội',
    serviceType: 'dining',
    subType: 'restaurant',
    location: { type: 'Point', coordinates: [105.8481, 21.0282] },
    address: '70 Nguyễn Du, Hai Bà Trưng, Hà Nội',
    serviceArea: 'Địa phương',
    contact: { phone: '024 3942 8162' },
    priceRange: 'Trung cấp',
    description: 'Nhà hàng phù hợp đoàn nội đô, dễ minh họa chi phí bữa trưa chương trình một ngày.',
    rating: 4.4,
    educationalNotes: 'Dùng tốt trong case estimate tuyến Hà Nội city tour.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Nhà hàng Hồng Hạnh 3',
    serviceType: 'dining',
    subType: 'restaurant',
    location: { type: 'Point', coordinates: [107.0523, 20.9505] },
    address: '50 Hạ Long, Bãi Cháy, Quảng Ninh',
    serviceArea: 'Địa phương',
    contact: { phone: '0203 3812 345' },
    priceRange: 'Trung cấp',
    description: 'Nhà hàng hải sản phù hợp đoàn công ty và tour khách nội địa tại Hạ Long.',
    rating: 4.5,
    educationalNotes: 'Minh họa chi phí ăn uống trong tour biển đảo phổ biến.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Morning Glory Original Hội An',
    serviceType: 'dining',
    subType: 'local_food',
    location: { type: 'Point', coordinates: [108.3279, 15.8788] },
    address: '106 Nguyễn Thái Học, Hội An',
    serviceArea: 'Địa phương',
    contact: { phone: '0235 2241 555' },
    priceRange: 'Trung cấp',
    description: 'Ẩm thực đặc trưng Hội An, phù hợp tour di sản và đoàn khảo sát chuyên đề.',
    rating: 4.7,
    educationalNotes: 'Có thể dùng để minh họa bản sắc ẩm thực trong thiết kế sản phẩm du lịch.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Xe du lịch Sao Việt',
    serviceType: 'transportation',
    subType: 'tour_bus',
    location: { type: 'Point', coordinates: [105.8544, 21.0285] },
    address: '45 Trần Nhật Duật, Hoàn Kiếm, Hà Nội',
    serviceArea: 'Vùng',
    contact: { phone: '024 3926 1234', website: 'https://saoviet.vn' },
    priceRange: 'Trung cấp',
    description: 'Nhà xe phục vụ tốt cho tour miền Bắc và đoàn khảo sát liên tỉnh.',
    rating: 4.4,
    educationalNotes: 'Phù hợp mô phỏng chi phí vận chuyển cho tuyến từ Hà Nội đi các tỉnh.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Cáp treo Bà Nà',
    serviceType: 'transportation',
    subType: 'cable_car',
    location: { type: 'Point', coordinates: [108.0037, 15.9994] },
    address: 'Bà Nà Hills, Hòa Vang, Đà Nẵng',
    serviceArea: 'Địa phương',
    contact: { phone: '0236 3749 888', website: 'https://banahills.sunworld.vn' },
    priceRange: 'Trung cấp',
    description: 'Dịch vụ vận chuyển đặc thù, tạo chênh lệch giá rõ trong chương trình miền Trung.',
    rating: 4.8,
    educationalNotes: 'Minh họa dịch vụ vận chuyển gắn với điểm vui chơi có vé cao.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Sun World Bà Nà Hills',
    serviceType: 'entertainment',
    subType: 'tourist_area',
    location: { type: 'Point', coordinates: [108.0037, 15.9994] },
    address: 'Thôn An Sơn, Hòa Vang, Đà Nẵng',
    serviceArea: 'Địa phương',
    contact: { phone: '1900 888 684', website: 'https://banahills.sunworld.vn' },
    priceRange: 'Cao cấp',
    description: 'Khu du lịch giải trí chủ lực, phù hợp case nghiên cứu doanh thu cao điểm.',
    rating: 4.8,
    educationalNotes: 'Dùng tốt để minh họa thành phần vé và upsell trong dự toán.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Trung tâm Hướng dẫn viên Miền Trung',
    serviceType: 'support',
    subType: 'guide',
    location: { type: 'Point', coordinates: [108.2208, 16.0678] },
    address: 'Hải Châu, Đà Nẵng',
    serviceArea: 'Vùng',
    contact: { phone: '0236 3555 888' },
    priceRange: 'Trung cấp',
    description: 'Đơn vị cung ứng hướng dẫn viên cho tour di sản và tour khảo sát.',
    rating: 4.5,
    educationalNotes: 'Minh họa nhóm dịch vụ hỗ trợ trong tổ chức tour học tập.',
    isRecommended: true,
    images: [],
    videos: [],
  },
  {
    name: 'Trung tâm thông tin du khách TP.HCM',
    serviceType: 'support',
    subType: 'other',
    location: { type: 'Point', coordinates: [106.7013, 10.7768] },
    address: '92-96 Nguyễn Huệ, Quận 1, TP.HCM',
    serviceArea: 'Địa phương',
    contact: { phone: '028 3823 4050' },
    priceRange: 'Bình dân',
    description: 'Điểm hỗ trợ thông tin và dịch vụ bổ trợ cho city tour.',
    rating: 4.2,
    educationalNotes: 'Có thể dùng giải thích vai trò dịch vụ bổ trợ trong trải nghiệm điểm đến.',
    isRecommended: false,
    images: [],
    videos: [],
  },
];

const tourismRoutes = [
  {
    routeName: 'Hà Nội Di sản học đường',
    description: 'Tuyến một ngày phục vụ học liệu về lịch sử, văn hóa và du lịch nội đô.',
    duration: '1 ngày',
    exploitationGuide: '## Hà Nội Di sản học đường\n\n### Đối tượng: Sinh viên, đoàn khảo sát ngắn ngày\n### Điểm mạnh: Chi phí gọn, dễ vận hành, giàu giá trị học thuật',
    pointNames: ['Hồ Hoàn Kiếm', 'Văn Miếu Quốc Tử Giám', 'Chùa Một Cột'],
  },
  {
    routeName: 'Hà Nội - Hạ Long trải nghiệm di sản biển',
    description: 'Tuyến khách đoàn phổ biến, phù hợp minh họa sản phẩm 2 ngày 1 đêm và khai thác dịch vụ cao cấp.',
    duration: '2 ngày 1 đêm',
    exploitationGuide: '## Hà Nội - Hạ Long trải nghiệm di sản biển\n\n### Đối tượng: Doanh nghiệp, khách nội địa, MICE quy mô vừa\n### Điểm mạnh: Dễ xây dựng báo giá, dịch vụ đồng bộ, hình ảnh sản phẩm rõ nét',
    pointNames: ['Hồ Hoàn Kiếm', 'Vịnh Hạ Long', 'Hang Sửng Sốt', 'Đảo Ti Tốp'],
  },
  {
    routeName: 'Di sản miền Trung mở rộng',
    description: 'Tuyến học liệu tiêu biểu cho nhóm tài nguyên văn hóa, lịch sử và vui chơi giải trí miền Trung.',
    duration: '4 ngày 3 đêm',
    exploitationGuide: '## Di sản miền Trung mở rộng\n\n### Đối tượng: Giảng viên, sinh viên, đoàn khảo sát chuyên đề\n### Điểm mạnh: Có đủ yếu tố di sản, cảnh quan, dịch vụ vé và lưu trú',
    pointNames: ['Cố đô Huế', 'Đèo Hải Vân', 'Bà Nà Hills', 'Phố cổ Hội An', 'Thánh địa Mỹ Sơn'],
  },
  {
    routeName: 'TP.HCM City Tour lịch sử - đô thị',
    description: 'Tuyến ngắn phù hợp minh họa city tour và sản phẩm nửa ngày hoặc một ngày cho khách đoàn.',
    duration: '1 ngày',
    exploitationGuide: '## TP.HCM City Tour lịch sử - đô thị\n\n### Đối tượng: Khách công vụ, đoàn ngoại khóa, city break\n### Điểm mạnh: Vận hành đơn giản, dễ lồng ghép mua sắm và dịch vụ bổ trợ',
    pointNames: ['Dinh Độc Lập', 'Chợ Bến Thành'],
  },
];

module.exports = {
  tourismPoints,
  serviceProviders,
  tourismRoutes,
};
